# Copyright (c) 2018-present, GM Cruise LLC
#
# This source code is licensed under the Apache License, Version 2.0,
# found in the LICENSE file in the root directory of this source tree.
# You may not use this file except in compliance with the License.

# This container is published at https://hub.docker.com/r/cruise/webviz-ci.

FROM cruise/webviz-ci:0.0.8

COPY . /opt/webviz
WORKDIR /opt/webviz

RUN npm run bootstrap
RUN npm run build

ENTRYPOINT ["/opt/webviz/docker_entrypoint.sh"]
CMD ["npm", "run", "serve"]
